#!/bin/bash -l
GIT_REPO=$HOME/jaan.io.git
TMP_GIT_CLONE=$HOME/tmp/
PUBLIC_WWW=/var/www/jaan.io
JEKYLL=jekyll

git clone $GIT_REPO $TMP_GIT_CLONE
$JEKYLL build -s $TMP_GIT_CLONE -d $PUBLIC_WWW
rm -Rf $TMP_GIT_CLONE
exit
